name: Bug Report | Bug 反馈
description: Create a report to help us improve | 创建报告以帮助我们改进
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the bug | 描述Bug
      description: A clear and concise description of what the bug is. | 清楚简洁地描述Bug是什么。
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce | 复现方法
      description: Steps to reproduce the behavior. | 复现该行为的步骤。
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior | 预期行为
      description: A clear and concise description of what you expected to happen. | 清楚简洁地描述你期望发生的事情。
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots | 截图
      description: If applicable, add screenshots to help explain your problem. | 如果适用，添加截图以帮助解释你的问题。
    
  - type: input
    attributes:
      label: Platform | 平台
      description: The platform you are using. (e.g. Windows 10) | 你正在使用的平台。（例如Windows 10）

  - type: input
    attributes:
      label: BDS Version | BDS版本
      description: The version of BDS you are using. (e.g. 1.20.32.1) | 你正在使用的BDS版本。（例如1.20.32.1）

  - type: input
    attributes:
      label: LeviLamina Version | LeviLamina版本
      description: The version of LeviLamina you are using. (e.g. 1.0.0) | 你正在使用的LeviLamina版本。（例如1.0.0）

  - type: input
    attributes:
      label: Version | 版本
      description: The version of the mod you are using. (e.g. 1.0.0) | 你正在使用的mod版本。（例如1.0.0）

  - type: textarea
    attributes:
      label: Additional context | 其他上下文
      description: Add any other context about the problem here. | 在这里添加关于问题的其他上下文。
